{{- $kubernetes := $.Values.kubernetes -}}
{{- $fullName := include "kubernetes.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: konnectivity-agent
    {{- with $kubernetes.konnectivityAgent.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $kubernetes.konnectivityAgent.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: kube-system
  name: konnectivity-agent
spec:
  replicas: {{ $kubernetes.konnectivityAgent.replicaCount }}
  {{- with $kubernetes.konnectivityAgent.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      k8s-app: konnectivity-agent
  template:
    metadata:
      labels:
        k8s-app: konnectivity-agent
        {{- with $kubernetes.konnectivityAgent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $kubernetes.konnectivityAgent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $kubernetes.konnectivityAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ $kubernetes.konnectivityAgent.hostNetwork }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      priorityClassName: system-cluster-critical
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      {{- with $kubernetes.konnectivityAgent.tolerations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if or $kubernetes.konnectivityServer.affinity $kubernetes.konnectivityServer.podAntiAffinity }}
      affinity:
        {{- with $kubernetes.konnectivityServer.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if eq $kubernetes.konnectivityServer.podAntiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "{{ $kubernetes.konnectivityServer.podAntiAffinityTopologyKey }}"
              labelSelector:
                matchLabels:
                  app: {{ $fullName }}-konnectivity-server
        {{- else if eq $kubernetes.konnectivityServer.podAntiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "{{ $kubernetes.konnectivityServer.podAntiAffinityTopologyKey }}"
                labelSelector:
                  matchLabels:
                    app: {{ $fullName }}-konnectivity-server
        {{- end }}
      {{- end }}
      imagePullSecrets: {{ include "pkg.images.registry.pullsecrets" $ | nindent 8 }}
        {{- with $kubernetes.konnectivityServer.image.pullSecrets }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: konnectivity-agent
        {{- with $kubernetes.konnectivityAgent.image }}
        image: {{ include "pkg.images.registry.convert" (dict "image" . "ctx" $) }}
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
        command:
        - /proxy-agent
        - --logtostderr=true
        - --ca-cert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --service-account-token-path=/var/run/secrets/tokens/konnectivity-agent-token

        {{- if not (hasKey $kubernetes.konnectivityAgent.extraArgs "proxy-server-host") }}
        {{- if and (eq $kubernetes.konnectivityServer.mode "HTTPConnect") $kubernetes.konnectivityServer.service.loadBalancerIP }}
        - --proxy-server-host={{ $kubernetes.konnectivityServer.service.loadBalancerIP }}
        {{- else if and (eq $kubernetes.konnectivityServer.mode "GRPC") $kubernetes.apiServer.service.loadBalancerIP }}
        - --proxy-server-host={{ $kubernetes.apiServer.service.loadBalancerIP }}
        {{- else }}
        {{- fail ".konnectivityAgent.extraArgs.proxy-server-host must be specified!" }}
        {{- end }}
        {{- end }}

        {{- if not (hasKey $kubernetes.konnectivityAgent.extraArgs "proxy-server-port") }}
        {{- if eq $kubernetes.konnectivityServer.service.type "LoadBalancer" }}
        - --proxy-server-port={{ $kubernetes.konnectivityServer.service.ports.agent }}
        {{- else if $kubernetes.konnectivityServer.service.NodePort }}
        - --proxy-server-port={{ $kubernetes.konnectivityServer.service.nodePorts.agent }}
        {{- else }}
        {{- fail ".konnectivityAgent.extraArgs.proxy-server-port must be specified!" }}
        {{- end }}
        {{- end }}

        - --admin-server-port={{ $kubernetes.konnectivityAgent.ports.admin }}
        - --health-server-port={{ $kubernetes.konnectivityAgent.ports.health }}

        {{- range $key, $value := $kubernetes.konnectivityAgent.extraArgs }}
        - --{{ $key }}={{ $value }}
        {{- end }}
        ports:
        - containerPort: {{ $kubernetes.konnectivityAgent.ports.admin }}
          name: admin
        - containerPort: {{ $kubernetes.konnectivityAgent.ports.health }}
          name: health
        volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: konnectivity-agent-token
        {{- with $kubernetes.konnectivityAgent.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ $kubernetes.konnectivityAgent.ports.health }}
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 15
      {{- with $kubernetes.konnectivityAgent.sidecars }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: konnectivity-agent
      volumes:
      - name: konnectivity-agent-token
        projected:
          sources:
          - serviceAccountToken:
              path: konnectivity-agent-token
              audience: system:konnectivity-server
      {{- with $kubernetes.konnectivityAgent.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
