{{- if (include "kubernetes.enabled" $) -}}
  {{- $kubernetes := $.Values.kubernetes -}}
  {{- if $kubernetes.etcd.enabled -}}
    {{- $fullName := include "kubernetes.fullname" . -}}
    {{- $component_name := "etcd" -}}
    {{- if $kubernetes.etcd.podDisruptionBudget -}}
---
apiVersion: {{ include "common.capabilities.policy.apiVersion" $ }}
kind: PodDisruptionBudget
metadata:
  name: "{{ $fullName }}-etcd"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec: {{- toYaml $kubernetes.etcd.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels: {{- include "kubernetes.labels" $ | nindent 6 }}
      {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
    {{- end -}}
  {{- end -}}
{{- end -}}
