{{- if (include "kubernetes.enabled" $) -}}
  {{- $manifest := $.Values.kubernetes.etcd -}}
  {{- $fullName := include "kubernetes.fullname" . -}}
  {{- $component_name := "etcd" -}}
  {{- if (include "pkg.components.metrics.enabled" (dict "metrics" $manifest.metrics "ctx" $)) -}}
    {{- if (include "pkg.components.serviceMonitor.enabled" (dict "sm" $manifest.metrics.serviceMonitor "ctx" $)) -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}-etcd-monitor
  namespace: {{ $manifest.metrics.serviceMonitor.namespace | default .Release.Namespace }}
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
    {{- with $manifest.metrics.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $manifest.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  {{- with $manifest.metrics.serviceMonitor.endpoint }}
  - interval: {{ .interval }}
    port: http-metrics
    path: /metrics
    scheme: http
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    {{- with .scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .metricRelabelings }}
    metricRelabelings: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .relabelings }}
    relabelings: {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with $manifest.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ . }}
  {{- end }}
  {{- with $manifest.metrics.serviceMonitor.targetLabels }}
  targetLabels: {{- toYaml . | nindent 4 }}
  {{- end }}
  podTargetLabels: {{- include "pkg.common.sm.podTargetLabels" $ | nindent 4 }}
  selector:
    matchLabels:
    {{- if $manifest.metrics.serviceMonitor.matchLabels }}
      {{- toYaml $manifest.metrics.serviceMonitor.matchLabels | nindent 6 }}
    {{- else }}
        {{- include "kubernetes.selectorLabels" $ | nindent 6 }}
        {{- include "pkg.common.labels.component" $ | nindent 6 }}: {{ $component_name }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
    {{- end -}}
  {{- end -}}
{{- end -}}
