{{- define "common.cronjob" -}}
{{- $root := . }}
{{- range $name, $component := .Values.components }}
{{- if $component.controller }}
{{- if eq $component.controller.type "CronJob" }}
{{- $cronjob := $component.controller }}
{{- if $cronjob.deploy }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "library.name" $root }}-{{ $name }}
  labels:
{{ include "library.labels.standard" $root | indent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  schedule: {{ $cronjob.schedule | default "* * * * *" | quote }}
  {{- if $cronjob.concurrencyPolicy }}
  concurrencyPolicy: {{ $cronjob.concurrencyPolicy | quote }}
  {{- end }}
  {{- if $cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $cronjob.failedJobsHistoryLimit }}
  {{- end }}
  {{- if $cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ $cronjob.startingDeadlineSeconds }}
  {{- end }}
  {{- if $cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $cronjob.successfulJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
{{ include "library.labels.stable" $root | indent 8 }}
        app.kubernetes.io/component: {{ $name }}
        {{- include "library.mapify" (dict "map" $cronjob.extraLabels "ctx" $root) | nindent 8 }}
        {{- if $cronjob.gatherMetrics }}
        gatherMetrics: "enabled"
        {{- end }}
      annotations:
        {{- include "library.mapify" (dict "map" $cronjob.extraAnnotations "ctx" $root) | nindent 8 }}
    spec:
{{- include "common.jobspec" (dict "root" $root "job" $cronjob "name" $name) | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
