{{- define "common.networkpolicy" -}}
{{- if .Values.networkpolicy }}
{{- if .Values.networkpolicy.deploy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "library.name" . }}-default
  labels:
{{ include "library.labels.standard" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}
{{- end }}

{{- $root := . }}
{{- range $name, $component := .Values.components }}
{{- if $component.networkpolicies }}
{{- range $networkpolicyname, $networkpolicy := $component.networkpolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "library.name" $root }}-{{ $name }}-{{ $networkpolicyname }}
  labels:
{{ include "library.labels.standard" $root | indent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "library.name" $root }}
      app.kubernetes.io/component: {{ $name }}
  policyTypes:
    {{- range $policytype := $networkpolicy.policyTypes }}
    - {{ $policytype | quote }}
    {{- end }}
  {{- if $networkpolicy.ingress }}
  {{- $section := $networkpolicy.ingress }}
  ingress:
    - from:
      {{- include "networkpolicy.sections" $section | indent 6 }}
  {{- end }}
  {{- if $networkpolicy.egress }}
  {{- $section := $networkpolicy.egress }}
  egress:
    - to:
      {{- include "networkpolicy.sections" $section | indent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
