{{- if .Values.includes.ingress }}
  {{- template "common.ingress.ingress" . }}
  {{- template "common.ingress.secret" . }}
{{- end }}

{{- if .Values.includes.service }}
  {{- template "common.service" . }}
{{- end -}}

{{- if .Values.includes.statefulset }}
  {{- template "common.statefulset" . }}
{{- end -}}

{{- if .Values.includes.deployment }}
  {{- template "common.deployment" . }}
{{- end -}}

{{- if .Values.includes.job }}
  {{- template "common.job" . }}
{{- end -}}

{{- if .Values.includes.cronjob }}
  {{- template "common.cronjob" . }}
{{- end -}}

{{- if .Values.includes.envSecret }}
  {{- template "common.controller.envSecret" . }}
{{- end -}}

{{- if .Values.includes.envConfigMap }}
  {{- template "common.controller.envConfigMap" . }}
{{- end -}}

{{- if .Values.includes.configFiles }}
  {{- template "common.controller.configFiles" . }}
{{- end -}}

{{- if .Values.includes.binaryFiles }}
  {{- template "common.controller.binaryFiles" . }}
{{- end -}}

{{- if .Values.includes.files }}
  {{- template "common.controller.files" . }}
{{- end -}}

{{- if .Values.includes.pvcs }}
  {{- template "common.pvcs" . }}
{{- end -}}

{{- if .Values.includes.servicemonitor }}
  {{- template "common.servicemonitor.headless.service" . }}
  {{- template "common.servicemonitor.servicemonitor" . }}
  {{- template "common.servicemonitor.secret" . }}
{{- end -}}

{{- if .Values.includes.networkpolicy }}
  {{- template "common.networkpolicy" . }}
{{- end -}}
