global: 
  components:    
    workloads:
      labels:
        components: "label"
      annotations: 
        components: "annotation"
      podLabels:
        components: "podLabels"
      podAnnotations:
        reloader.stakater.com/auto: "true"
      image:
        pullPolicy: "Always"
        pullSecrets:
          - name: "common-regcred"
      podSecurityContext:
        enabled: false
      # -- Enable Pod Security Context for all workloads
      #  enabled: true
      #  seccompProfile:
      #    type: RuntimeDefault
  
      # -- Container Security Context for all workloads (Overwrites per workload securityContext)
      securityContext:
        enabled: false
      # -- Enable Pod Security Context for all workloads
      #  enabled: true
      #  allowPrivilegeEscalation: false
      #  capabilities:
      #    drop:
      #    - ALL
      #  readOnlyRootFilesystem: true
  
      # -- Node Selector for all workloads (Overwrites all workloads nodeSelector)
      nodeSelector: 
        components: "nodeSelector"
      # -- Tolerations for all workloads (Overwrites all workloads tolerations)
      tolerations: []
      # -- Affinity for all workloads (Overwrites all workloads affinities)
      affinity: {}
      # -- Priority Class for all workloads (Overwrites all workloads priorityClassNames)
      priorityClassName: "components"
      # -- TopologySpreadConstraints for all workloads (Overwrites all workloads topologySpreadConstraints)
      topologySpreadConstraints: []

lifecycle:
  job:
    reconciler: true
    labels: 
      argocd.argoproj.io/hook: PreSync
    annotations:
      argocd.argoproj.io/hook: PreSync
  current:
    extraManifests:
      project.yaml: |
        {{- include "pkg.manifests.argo-cluster-project" $ | nindent 4 }}
      bootstrap-app.yaml: |
        {{- include "pkg.manifests.argo-bootstrap-app" $ | nindent 4 }}
      bootstrap-app-ejson.yaml: |
        {{- include "pkg.manifests.argo-app-ejson"  $ | nindent 4 }}
      bootstrap-repository.yaml: |
        {{- include "pkg.manifests.argo-bootstrap-repository" $ | nindent 4 }}
  vcluster:
    extraManifests:
      bootstrap-app-ejson.yaml: |
        {{- include "pkg.manifests.argo-app-ejson"  $ | nindent 4 }}
gitops:
  enabled: false
osm:
  enabled: false
kubernetes:
  enabled: false
autoscaler:
  enabled: false
machine:
  enabled: false
