{{- $manifest := $.Values.lifecycle.job -}}
{{- if $manifest.reconciler }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gitops.fullname" .  }}-lifecycle
  labels: {{- include "gitops.labels" $ | nindent 4 }}
    {{- with $manifest.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $manifest.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: "{{ $manifest.schedule }}"
  successfulJobsHistoryLimit: {{ $manifest.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $manifest.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels: {{- include "gitops.labels" $ | nindent 8 }}
        {{- with $manifest.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/scripts: {{ .Files.Get "/templates/scripts-configmap.yaml" | sha256sum  }}
        {{- with $manifest.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      template:
      {{- (include (print $.Template.BasePath "/lifecycle/job.yaml") . | fromYaml ).spec.template | toYaml | nindent 8 }}
{{- end -}}
