
{{/* Inventory Sync with Flux Resources */}}
{{- $manifest := $.Values.gitops -}}
{{- $inventory := $manifest.inventory -}}
{{- if (include "gitops.flux.enabled" $) -}}
  {{- if $inventory.enabled -}}
  {{- $name := printf "%s-inventory" (include "gitops.fullname" $) -}}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ $name }}
  labels: {{- include "gitops.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ default "5m" $manifest.flux.interval }}
  ref:
    branch: {{ include "gitops.inventory.reference" $ }}
  url: {{ required "Repository URL for Inventory is required ($.Values.gitops.inventory.repository.url)" $inventory.repository.url }}
    {{- if or ($manifest.token) ($inventory.repository.token) }}
  secretRef:
    name: {{ $name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels: {{- include "gitops.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
stringData:
      {{- if $manifest.token }}
  password: {{ $manifest.token }}
      {{- end }}
      {{- if $inventory.repository.token }}
  password: {{ $inventory.repository.token }}
      {{- end }}
  username: "token"
    {{- end }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ $name }}
  labels: {{- include "gitops.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  interval: {{ default "5m" $manifest.flux.interval  }}
  prune: {{ $manifest.flux.prune }}
  path: {{ include "gitops.inventory.path" $ }}
  sourceRef:
    kind: GitRepository
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "gitops.converter.flux.secretName" $ }}
      key: {{ include "gitops.converter.secretKey" $ }}
  {{- with $manifest.flux.secretReference }}
    {{- if .enabled }}
  decryption:
    provider: sops
    secretRef:
      name: {{ .name }}
    {{- end }}
  {{- end }}
  postBuild:
    substituteFrom:
      - kind: Secret
        name: {{ include "gitops.fullname" $ }}-flux-subs
  {{- end -}}
{{- end -}}
