{{- if (include "kubernetes.enabled" $) -}}
  {{- $kubernetes := $.Values.kubernetes -}}
  {{- if and $kubernetes.konnectivityServer.enabled $kubernetes.konnectivityServer.service.enabled (eq $kubernetes.konnectivityServer.mode "HTTPConnect") }}
    {{- $fullName := include "kubernetes.fullname" . -}}
    {{- $component_name := "konnectivity" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-konnectivity-server
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{- include "pkg.components.svc_labels" (dict "labels" $kubernetes.konnectivityServer.service.labels "ctx" $) | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  annotations:
    {{- include "pkg.components.svc_annotations" (dict "annotations" $kubernetes.konnectivityServer.service.annotations "ctx" $) | nindent 4 }}
spec:
  type: {{ $kubernetes.konnectivityServer.service.type }}
  {{- with $kubernetes.konnectivityServer.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - port: {{ $kubernetes.konnectivityServer.ports.server }}
    name: server
    {{- with $kubernetes.konnectivityServer.service.nodePorts.server }}
    nodePort: {{ . }}
    {{- end }}
  - port: {{ $kubernetes.konnectivityServer.ports.agent }}
    name: agent
    {{- with $kubernetes.konnectivityServer.service.nodePorts.client }}
    nodePort: {{ . }}
    {{- end }}
  selector: {{- include "kubernetes.selectorLabels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  {{- end }}
{{- end }}
