{{- if (include "pkg.components.netpol.enabled" $) -}} 
  {{- if (include "kubernetes.enabled" $) -}}
    {{- $kubernetes := $.Values.kubernetes -}}
    {{- if and $kubernetes.konnectivity.enabled $kubernetes.konnectivity.server.enabled -}}
      {{- if or (eq $kubernetes.konnectivity.server.mode "HTTPConnect") (not $kubernetes.konnectivity.server.sidecar) -}}
        {{- $fullName := include "kubernetes.fullname" . -}}
        {{- $component_name := "konnectivity" -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ $fullName }}-konnectivity-server"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
      {{- include "kubernetes.labels" $ | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: {{ $kubernetes.konnectivity.server.ports.agent }}
        {{- with (include "pkg.components.netpol.from" (dict "ctx" $ "np" $kubernetes.konnectivity.server.networkPolicy )) }}
    from: {{ . | nindent 6 }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}