{{- if (include "kubernetes.enabled" $) -}}
  {{- $kubernetes := $.Values.kubernetes -}}
  {{- $fullName := include "kubernetes.fullname" . -}}
  {{- $certName := include "kubernetes.certname" . -}}
  {{- $component_name := "kubernetes" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-ca"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ $certName }}-ca"
  secretName: "{{ $fullName }}-pki-ca"
  duration: 87600h # 3650d
  renewBefore: 8760h # 365d
  subject:
    organizations:
    - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "cert sign"
  isCA: true
  issuerRef:
    {{- include "pkg.components.certificates.issuer" $ | nindent 4 }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ $fullName }}-issuer"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: "{{ $fullName }}-pki-ca"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-sa"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ $certName }}-sa"
  secretName: "{{ $fullName }}-pki-sa"
  duration: 87600h # 3650d
  renewBefore: 8760h # 365d
  subject:
    organizations:
    - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "cert sign"
  isCA: true
  issuerRef:
    name: "{{ $fullName }}-selfsigning-issuer"
    kind: Issuer
---
{{- $svcName1 := printf "%s-controller-manager" $fullName }}
{{- $svcName2 := printf "%s-controller-manager.%s" $fullName .Release.Namespace }}
{{- $svcName3 := printf "%s-controller-manager.%s.svc" $fullName .Release.Namespace }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-controller-manager-server"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ $certName }}-controller-manager-server"
  secretName: "{{ $fullName }}-pki-controller-manager-server"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "server auth"
  dnsNames:
  - "{{ $svcName1 }}"
  - "{{ $svcName2 }}"
  - "{{ $svcName3 }}"
  {{- with $kubernetes.apiServer.certSANs.dnsNames }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  ipAddresses:
  - "127.0.0.1"
  - "{{- template "kubernetes.getAPIAddress" . }}"
  {{- with (include "kubernetes.api.endpointIP" $) }}
  - {{ . }}
  {{- end }}
  {{- with $kubernetes.apiServer.service.loadBalancerIP }}
  {{- if not (has . $kubernetes.apiServer.certSANs.ipAddresses) }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with $kubernetes.apiServer.certSANs.ipAddresses }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
---
{{- $svcName1 := printf "%s-scheduler" $fullName }}
{{- $svcName2 := printf "%s-scheduler.%s" $fullName .Release.Namespace }}
{{- $svcName3 := printf "%s-scheduler.%s.svc" $fullName .Release.Namespace }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-scheduler-server"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ $certName }}-scheduler-server"
  secretName: "{{ $fullName }}-pki-scheduler-server"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "server auth"
  dnsNames:
  - "{{ $svcName1 }}"
  - "{{ $svcName2 }}"
  - "{{ $svcName3 }}"
  - "localhost"
  {{- with $kubernetes.apiServer.certSANs.dnsNames }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  ipAddresses:
  - "127.0.0.1"
  - "{{- template "kubernetes.getAPIAddress" . }}"
  {{- with (include "kubernetes.api.endpointIP" $) }}
  - {{ . }}
  {{- end }}
  {{- with $kubernetes.apiServer.service.loadBalancerIP }}
  {{- if not (has . $kubernetes.apiServer.certSANs.ipAddresses) }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with $kubernetes.apiServer.certSANs.ipAddresses }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
---
{{- $svcName1 := printf "%s-apiserver" $fullName }}
{{- $svcName2 := printf "%s-apiserver.%s" $fullName .Release.Namespace }}
{{- $svcName3 := printf "%s-apiserver.%s.svc" $fullName .Release.Namespace }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-apiserver-server"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ $certName }}-apiserver-server"
  secretName: "{{ $fullName }}-pki-apiserver-server"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "server auth"
  dnsNames:
  - "{{ $svcName1 }}"
  - "{{ $svcName2 }}"
  - "{{ $svcName3 }}"
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.{{ $kubernetes.networking.dnsDomain | trimAll "." }}
  - "localhost"
  {{- with $kubernetes.apiServer.certSANs.dnsNames }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  ipAddresses:
  - "127.0.0.1"
  - "{{- template "kubernetes.getAPIAddress" . }}"
  {{- with (include "kubernetes.api.endpointIP" $) }}
  - {{ . }}
  {{- end }}
  {{- with $kubernetes.apiServer.service.loadBalancerIP }}
  {{- if not (has . $kubernetes.apiServer.certSANs.ipAddresses) }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with $kubernetes.apiServer.certSANs.ipAddresses }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-controller-manager-client"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "system:kube-controller-manager"
  secretName: "{{ $fullName }}-pki-controller-manager-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "system:kube-controller-manager"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-scheduler-client"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "system:kube-scheduler"
  secretName: "{{ $fullName }}-pki-scheduler-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "system:kube-scheduler"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-konnectivity-server-client"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "system:konnectivity-server"
  secretName: "{{ $fullName }}-pki-konnectivity-server-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "system:konnectivity-server"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-admin-client"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ $certName }}-admin-client"
  secretName: "{{ $fullName }}-pki-admin-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "system:masters"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-apiserver-kubelet-client"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "{{ $certName }}-apiserver-kubelet-client"
  secretName: "{{ $fullName }}-pki-apiserver-kubelet-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "system:masters"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
{{- end }}
