{{- if (include "kubernetes.enabled" $) -}}
  {{- $kubernetes := $.Values.kubernetes -}}
  {{- if $kubernetes.scheduler.enabled }}
    {{- $fullName := include "kubernetes.fullname" . -}}
    {{- $component_name := "scheduler" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-scheduler-conf
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
data:
  kubeconfig.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /pki/scheduler-client/ca.crt
        server: {{ include "kubernetes.api.url" $ }}
      name: default-cluster
    contexts:
    - context:
        cluster: default-cluster
        namespace: default
        user: default-auth
      name: default-context
    current-context: default-context
    kind: Config
    preferences: {}
    users:
    - name: default-auth
      user:
        client-certificate: /pki/scheduler-client/tls.crt
        client-key: /pki/scheduler-client/tls.key

  {{- if $kubernetes.scheduler.configuration }}
  scheduler.yaml: |
    {{- include "pkg.utils.template" (dict "tpl" $kubernetes.scheduler.configuration "ctx" $) | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
