---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "vcluster.fullname" $ }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vcluster.labels" $ | nindent 4 }}
spec:
  dnsNames:
  {{- with (include "pkg.common.ingress.host" $) }}
  - {{ . }}
  {{- end }}
  usages:
  - "signing"
  - "key encipherment"
  - "server auth"
  issuerRef:
    {{- include "pkg.common.certificates.issuer" $ | nindent 4 }}
  secretName: {{ include "pkg.common.certificates.secretTlsName" $ }}
