{{- if (include "operating-system-manager.enabled" $) -}}
  {{- $manifest := $.Values.osm -}}
  {{- if $manifest.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operating-system-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operating-system-manager.labels" . | nindent 4 }}
    {{- with $manifest.serviceAccount.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end -}}
{{- end -}}
