{{- if (include "machine-controller.enabled" $) -}}
  {{- $providers := $.Values.providers -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "machine-controller.fullname" . }}-providers
  labels:
    {{- include "machine-controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- with $nutanix := $providers.nutanix }}
    {{- with $nutanix.endpoint }}
  NUTANIX_ENDPOINT: {{ . | quote }}
    {{- end }}
    {{- with $nutanix.port }}
  NUTANIX_PORT: {{ . | quote }}
    {{- end }}
    {{- with $nutanix.username }}
  NUTANIX_USERNAME: {{ . | quote }}
    {{- end }}
    {{- with $nutanix.password }}
  NUTANIX_PASSWORD: {{ . | quote }}
    {{- end }}
    {{- with $nutanix.proxy }}
  NUTANIX_PROXY_URL: {{ . | quote}}
    {{- end }}
    {{- with $nutanix.cluster }}
  NUTANIX_CLUSTER_NAME: {{ . | quote }}
    {{- end }}
    {{- with $nutanix.insecure }}
  NUTANIX_INSECURE: {{ . | quote }}
    {{- end }}
  {{- end }}
{{- end -}}
