{{- if (include "machine-controller.enabled" $) -}}
  {{- $manifest := $.Values.machine -}}
  {{- if $manifest.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "machine-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "machine-controller.labels" $ | nindent 4 }}
    {{- with $manifest.serviceAccount.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
