name: Helm Chart Release
on:
  push:
    branches:
      - master

jobs:

  documentation:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:

      - name: Install Dependencies
        run: |
          apk add jq git curl

      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Install Helm Docs
        run: |
          curl -s -L -o /usr/local/bin/helm-docs.tar.gz "https://github.com/norwoodj/helm-docs/releases/download/$(curl --silent "https://api.github.com/repos/norwoodj/helm-docs/releases/latest" | jq -r .tag_name)/helm-docs_$(curl --silent "https://api.github.com/repos/norwoodj/helm-docs/releases/latest" | jq -r .tag_name | cut -d "v" -f2-)_Linux_x86_64.tar.gz"
          cd /usr/local/bin/ && tar xfv helm-docs.tar.gz
          chmod +x ./helm-docs

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Helm Chart Publish
        uses: buttahtoast/helm-release-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          schema: true
